version: "3.7"

services:
  app1:
    build: .
    ports:
      - "8082:8082"
    networks:
      - configstore_tux_network
    environment:
      MONGO_URL: mongodb://mongodb:27017
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27018:27017"
    networks:
      - configstore_tux_network
networks:
  configstore_tux_network:
    external: true
volumes:
  monogo-user-data: